Name: phn
Mode: dev

Pulsar:
  Url: "pulsar://localhost:6650"
  Main: "persistent://echo-wing/main"
  Dlq: "persistent://echo-wing/dlq/all"

Consul:
  Host: "localhost"
  Port: 8500
  Base: "echo_wing/"
  Token: ""
  Scheme: "http"

Modem:
  BaudRate: 115200
  TimeOut: 10.0
  UsbVPid:
    - "2c7c:0125"
  Patterns:
    - "/dev/ttyUSB*"
